#!/bin/bash

# if any of the commands in your code fails for any reason, the entire script fails
set -o errexit
# fail exit if one of your pipe command fails
set -o pipefail
# exits if any of your variables is not set
set -o nounset

# Wait for Elasticsearch
echo "Waiting for Elasticsearch..."
until curl -s http://elasticsearch:9200 > /dev/null; do
  sleep 2
done

# used to make the entrypoint a pass through to ensure that Docker 
# runs the command the user passes in (command: /start, in our case)
exec "$@"